name: Sync GH Pages
on:
  push:
    branches:
    - main
    paths:
    - library/**
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: everlytic/branch-merge@1.1.4
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'gh-pages'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'